/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import java.io.File;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Produtos;
import utils.Utils;

/**
 *
 * @author Lenovo
 */
public class FrAltProduto extends javax.swing.JDialog {

    private Produtos prod;

    /**
     * Creates new form FrAltProduto
     */
    public FrAltProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setProduto(Produtos prod) {
        this.prod = prod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblNomeProduto = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        lblValorProduto = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantia = new javax.swing.JTextField();
        btnAumentar = new javax.swing.JButton();
        btnDiminuir = new javax.swing.JButton();
        lblImgProduto = new javax.swing.JLabel();
        btnAltImg = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(244, 255, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(java.awt.Color.red);
        lblTitulo.setText("Alterar Produtos");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caneta64px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        lblCode.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lblCode.setText("Código:");
        jPanel1.add(lblCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtCode.setEditable(false);
        txtCode.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, -1));

        lblNomeProduto.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lblNomeProduto.setText("Nome do produto:");
        jPanel1.add(lblNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        jPanel1.add(txtNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 250, -1));

        lblValorProduto.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lblValorProduto.setText("Valor:");
        jPanel1.add(lblValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jPanel1.add(txtValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 60, -1));

        lblQuantidade.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lblQuantidade.setText("Quantidade no estoque:");
        jPanel1.add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        txtQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantiaActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 50, -1));

        btnAumentar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnAumentar.setText("+");
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 20));

        btnDiminuir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnDiminuir.setText("-");
        jPanel1.add(btnDiminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, 20));

        lblImgProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImgProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 140, 140));

        btnAltImg.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnAltImg.setText("Alterar imagem");
        btnAltImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltImgMouseClicked(evt);
            }
        });
        jPanel1.add(btnAltImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 130, 40));

        btnSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save24px.png"))); // NOI18N
        btnSalvar.setText("Salvar alterações");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantiaActionPerformed

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAumentarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregarProduto();

        URL caminhoImagem = getClass().getResource("/images/poke32px.png");

        ImageIcon icon = new ImageIcon(caminhoImagem);

        //DEFINE A IMAGEM
        this.setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowOpened

    private void btnAltImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltImgMouseClicked
        //CRIA UM ESCOLHEDOR DE ARQUVOS
        JFileChooser exploradorArquivos = new JFileChooser();

        //DEFINE O TITULO QUE APARECERA NA JANELA DO EXPLORADOR DE ARQUIVOS
        exploradorArquivos.setDialogTitle("Escolha um arquivo");

        //FILTRAR OS TIPOS DE ARQUIVOS QUE IRÁ BUSCAR
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens", "jpg", "jpeg", "png");
        exploradorArquivos.setFileFilter(filtro);

        //CONFIGURAÇÕES PARA PERMITIR A SELEÇÃO DE APENAS UM ARQUIVO
        exploradorArquivos.setMultiSelectionEnabled(false);

        /*Chama o explorador de arquivos e guarda o resultado:
        APPROVE_OPTION (selecionou)
        CANCEL_OPTION (usuário cancelou)*/
        int resultado = exploradorArquivos.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            //PEGA O ARQUIVO SELECIONADO
            File arquivo = exploradorArquivos.getSelectedFile();

            //Converte para um ícone
            Icon icone = Utils.converterFileParaIcon(arquivo);

            //Redimensiona para o tamanho que irá aparecer na tela
            ImageIcon iconeRedimensionado = Utils.redimensionarIcon(icone, 140, 140);

            //Coloca o icone na label da tela
            lblImgProduto.setIcon(iconeRedimensionado);
        }
    }//GEN-LAST:event_btnAltImgMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (verificarCampos() == true) {
            gravar();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    public void carregarProduto() {
        //Vamos buscar no banco de dados o restante dos campos do usuario,
        //atualmente só tem o pk

        ProdutoController controller = new ProdutoController();

        prod = controller.buscarPorPk(prod.getPkProduto());

        String codigo = String.valueOf(prod.getPkProduto());
        txtCode.setText(codigo);

        txtNomeProduto.setText(prod.getNomeProduto());

        String valorProd = String.valueOf(prod.getValorProduto());
        txtValorProduto.setText(valorProd);

        String quantProd = String.valueOf(prod.getQuantia());
        txtQuantia.setText(quantProd);

        lblImgProduto.setIcon(prod.getImgProduto());

        //txtValorProduto.setDouble(prod.getValorProduto());//VALOR PRECISA SER CONVERTIDO
        //txtQuantia.setText(prod.getQuantia());//VALOR PRECISA SER CONVERTIDO
    }

    /////////////////////////////////////////////////////////////////////////////
    //verificação de campos
    public boolean verificarCampos() {
        if (txtNomeProduto.equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome do produto' está vazio!");
            return false;
        }

        if (!txtNomeProduto.getText().matches("^[\\p{L}0-9 ]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Nome do produto' possui caracteres inválidos!");
            return false;
        }

        if (txtValorProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Valor' está vazio!");
            return false;
        }

        if (!txtValorProduto.getText().matches(
                "^[0-9]+.[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Valor' possui caracteres inválidos!");
        }

        if (txtQuantia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Quantidade' está vazio!");
            return false;
        }

        if (!txtQuantia.getText().matches(
                "^[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Quantidade' possui caracteres inválidos!");
            return false;
        }
        return true;
    }

    public void gravar() {
        //vai atualizar os dados do atributo usuario

        prod.setNomeProduto(txtNomeProduto.getText());

        //String valorProd = String.valueOf(prod.getValorProduto());
        //txtValorProduto.setText(valorProd);
        String valorProdStr = txtValorProduto.getText();
        double valorProd = Double.parseDouble(valorProdStr);
        prod.setValorProduto(valorProd);

        String quantProdStr = txtQuantia.getText();
        double quantProd = Double.parseDouble(quantProdStr);
        prod.setQuantia(quantProd);

        prod.setImgProduto(lblImgProduto.getIcon());

        ProdutoController controller = new ProdutoController();

        if (controller.alterarProduto(prod)) {
            JOptionPane.showMessageDialog(null, "Produto: " + prod.getNomeProduto() + " alterado com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não pode ser alterado!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltProduto dialog = new FrAltProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltImg;
    private javax.swing.JButton btnAumentar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDiminuir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblImgProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQuantia;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
