/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author s.lucas
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        imVenda = new javax.swing.JMenuItem();
        imUsuario = new javax.swing.JMenuItem();
        imProdutos = new javax.swing.JMenuItem();
        imSair = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        imConVendas = new javax.swing.JMenuItem();
        imConProdutos = new javax.swing.JMenuItem();
        imConUsuario = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(244, 255, 212));

        lbImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poke128px.png"))); // NOI18N
        lbImagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        menuCadastro.setText("Cadastro");

        imVenda.setText("Venda");
        imVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imVendaActionPerformed(evt);
            }
        });
        menuCadastro.add(imVenda);

        imUsuario.setText("Usuário");
        imUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imUsuarioMouseClicked(evt);
            }
        });
        imUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(imUsuario);

        imProdutos.setText("Produto");
        imProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(imProdutos);

        imSair.setText("Sair");
        imSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imSairActionPerformed(evt);
            }
        });
        menuCadastro.add(imSair);

        barraMenu.add(menuCadastro);

        menuConsulta.setText("Consulta");

        imConVendas.setText("Vendas");
        imConVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConVendasActionPerformed(evt);
            }
        });
        menuConsulta.add(imConVendas);

        imConProdutos.setText("Produtos");
        imConProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConProdutosActionPerformed(evt);
            }
        });
        menuConsulta.add(imConProdutos);

        imConUsuario.setText("Usuário");
        imConUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imConUsuarioActionPerformed(evt);
            }
        });
        menuConsulta.add(imConUsuario);

        barraMenu.add(menuConsulta);

        menuSobre.setText("Sobre");
        menuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSobreMouseClicked(evt);
            }
        });
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        barraMenu.add(menuSobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_imSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        URL caminhoImagem = getClass().getResource("/images/poke32px.png");

        ImageIcon icon = new ImageIcon(caminhoImagem);

        //DEFINE A IMAGEM
        this.setIconImage(icon.getImage());

    }//GEN-LAST:event_formWindowOpened

    private void imUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imUsuarioActionPerformed
        FrCadUsuario telaCadastro = new FrCadUsuario(this, rootPaneCheckingEnabled);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_imUsuarioActionPerformed

    private void imUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imUsuarioMouseClicked

    }//GEN-LAST:event_imUsuarioMouseClicked

    private void imConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConUsuarioActionPerformed
        FrConUsuario telaConsulta = new FrConUsuario(this, rootPaneCheckingEnabled);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_imConUsuarioActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed

    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSobreMouseClicked
        FrSobre telaSobre = new FrSobre(this, rootPaneCheckingEnabled);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_menuSobreMouseClicked

    private void imVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imVendaActionPerformed
        FrVendas telaCadastroVendas = new FrVendas(this, rootPaneCheckingEnabled);
        telaCadastroVendas.setVisible(true);
    }//GEN-LAST:event_imVendaActionPerformed

    private void imProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imProdutosActionPerformed
        FrCadastrarProdutos telaCadastroProd = new FrCadastrarProdutos(this, rootPaneCheckingEnabled);
        telaCadastroProd.setVisible(true);
    }//GEN-LAST:event_imProdutosActionPerformed

    private void imConVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConVendasActionPerformed
        FrConVenda telaConsultaVenda = new FrConVenda(this, rootPaneCheckingEnabled);
        telaConsultaVenda.setVisible(true);
    }//GEN-LAST:event_imConVendasActionPerformed

    private void imConProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imConProdutosActionPerformed
        FrBuscarProdutos telaConsultarProduto = new FrBuscarProdutos(this, rootPaneCheckingEnabled);
        telaConsultarProduto.setVisible(true);
    }//GEN-LAST:event_imConProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem imConProdutos;
    private javax.swing.JMenuItem imConUsuario;
    private javax.swing.JMenuItem imConVendas;
    private javax.swing.JMenuItem imProdutos;
    private javax.swing.JMenuItem imSair;
    private javax.swing.JMenuItem imUsuario;
    private javax.swing.JMenuItem imVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuSobre;
    // End of variables declaration//GEN-END:variables
}
