/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.VendasController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Venda;
import utils.Utils;

/**
 *
 * @author Lenovo
 */
public class FrVendas extends javax.swing.JDialog {

    Utils utils = new Utils();

    /**
     * Creates new form FrVendas
     */
    public FrVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblIconLoja = new javax.swing.JLabel();
        lblDataVenda = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JTextField();
        lblValorVenda = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblCpfComprador = new javax.swing.JLabel();
        txtCpfComprador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeComprador = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 255, 212));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitle.setForeground(java.awt.Color.red);
        lblTitle.setText("Vendas");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblIconLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/poke64px.png"))); // NOI18N
        jPanel1.add(lblIconLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lblDataVenda.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDataVenda.setText("Data da venda:");
        jPanel1.add(lblDataVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        jPanel1.add(txtDataVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 70, 30));

        lblValorVenda.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblValorVenda.setText("Total:");
        jPanel1.add(lblValorVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 30));

        lblCpfComprador.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblCpfComprador.setText("CPF do comprador:");
        jPanel1.add(lblCpfComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(txtCpfComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Nome do comprador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(txtNomeComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, -1));

        btnCancel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close16.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save24px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (verificarCampos() == true) {
            gravar();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    public boolean verificarCampos() {

        Venda venda = new Venda();

        if (txtDataVenda.equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Data da venda' deve ser preenchido!");
            return false;
        }

        if (!txtDataVenda.getText().matches("^[0-9]+/[0-9]+/[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Data da venda' possui caracteres inválidos!"
                    + " Ex.: 01/01/1990");
            return false;
        }

        if (txtValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo 'Valor' deve ser preenchido!");
            return false;
        }

        if (!txtValorTotal.getText().matches(
                "^[0-9]+.[0-9]+$")) {
            JOptionPane.showMessageDialog(null, "O campo 'Valor' possui caracteres inválidos!");
        }

        if (txtNomeComprador.getText().equals("")) {
            venda.setNomeComprador(null);
        }

        if (txtCpfComprador.getText().equals("")) {
            venda.setCpfComprador(null);
        }

        return true;
    }

    public void gravar() {
        //INSTANCIAR UM OBJETO VENDA
        Venda venda = new Venda();

        Date data = Utils.converterStringToDate(txtDataVenda.getText());
        venda.setDataVenda(data);

        double valorTotal = Double.parseDouble(txtValorTotal.getText());
        venda.setValorTotal(valorTotal);

        venda.setNomeComprador(txtNomeComprador.getText());

        venda.setCpfComprador(txtCpfComprador.getText());

        VendasController controller = new VendasController();

        if (controller.inserirVenda(venda)) {
            JOptionPane.showMessageDialog(null, "Venda inserida com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Venda não pode ser inserida!");
        }
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrVendas dialog = new FrVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpfComprador;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblIconLoja;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValorVenda;
    private javax.swing.JTextField txtCpfComprador;
    private javax.swing.JTextField txtDataVenda;
    private javax.swing.JTextField txtNomeComprador;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
